# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef4d750ba02ff35a19474858dbc97b1a4dec6f841880d4518d0ae98d13c2d376691679e2aa1a508e84b0f1775296698463bc42a7db10c9a87bb6ec4cb81bf0d

test:
  secret_key_base: a17f1f48c457b7d2c85948c73de9d7ea9513a3a03037aed57f6fdbeaf547f3772f4fc49b601becd7406948d69b60fa4fc1a50bb5aa4237970d28b30b67d982ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
